

from .azure import copy_file_from_one_folder_to_another
from .dataverse import update_attachment_as_successfully_processed, get_attachments_not_uploaded_to_datev, update_attachment_as_uploaded_to_datev
__all__ = ["copy_file_from_folder_to_another","update_attachment_as_successfully_processed","get_access_token_for_graph_api","get_attachments_not_uploaded_to_datev","update_attachment_as_uploaded_to_datev"]
